### ISSUE TITLE
Lindley Design

### ISSUE THREAD

**Issue by SebastianUniTue** [fgoepp/tp23-statistical-illusions#19]
- Color matching variables for distribution
- values under plot 
- explain plot
- test right sided -> move only to right
- a bit of setting (what is it)
- (percentage 0-1)

## EDIT
- frequentist and bayesian are arguing, but both are right panel

**Comment by annazonked** [comment]
This issue was resolved by #46, 
besides the point of "frequentist and bayesian are arguing, but both are right panel" which we decided on maybe adding later.
